### ISSUE TITLE
mediapipe>=0.10.30 breaks telemoma due to unpinned dependency

### ISSUE THREAD

**Issue by han-xudong** [UT-Austin-RobIn/telemoma#5]
## Problem description

The current `setup.py` does not pin the version of `mediapipe`, which causes pip to install the latest version by default. However, mediapipe versions `>=0.10.30` remove or refactor several Python APIs and internal modules that telemoma depends on, leading to runtime errors.

## Steps to reproduce

```bash
pip install telemoma
python -c "from telemoma.human_interface.teleop_policy import TeleopPolicy"
```

After installation, importing `TeleopPolicy` results in errors as:

```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "xxx/telemoma/telemoma/human_interface/teleop_policy.py", line 2, in <module>
    from telemoma.human_interface.vision import VisionTeleopPolicy
  File "xxx/telemoma/telemoma/human_interface/vision.py", line 1, in <module>
    from mediapipe import solutions
ImportError: cannot import name 'solutions' from 'mediapipe' (xxx/mediapipe/__init__.py)
```

## Expected behavior

telemoma should install and run correctly with a compatible mediapipe version.

## Root cause

Starting from mediapipe `0.10.30`, several Python APIs and internal modules used by telemoma were removed or reorganized.
The current codebase has been verified to work correctly with mediapipe `0.10.21`.

## Proposed solution

Pin mediapipe to version `0.10.21` in setup.py to ensure compatibility and reproducibility.
